Deneb
bloxapp/beacon-kit pull request #2
Opened 2024-01-16 09:47 UTC by moshe-blox

2024-01-17 13:37 UTC, y0sher commented on go-eth2-client/client.go
> +	}
not checking `.Data` here?

2024-01-17 13:38 UTC, y0sher commented on go-eth2-client/client.go
> +	}
no need to check `resp.Data` here?

2024-01-17 13:39 UTC, y0sher commented on go-eth2-client/client.go
> +	return resp, nil
no need to check `.Data` ? I know its check on the calling function but on some functions here you do check it.

2024-01-17 13:39 UTC, y0sher commented on go-eth2-client/client.go
> +	return resp, nil
check `.Data`?

2024-01-17 13:40 UTC, y0sher requested changes
some places you check `Data` some not, lets unify

2024-01-21 12:43 UTC, moshe-blox commented on go-eth2-client/client.go
> +	}
i tried, however Go's generics are not flexible enough and the wrapper function ends up being too obscure (requires reflection or multiple diff. wrappers), in which case i prefer repetition :-)

2024-01-21 12:45 UTC, moshe-blox commented on go-eth2-client/client.go
> +	}
this should preserve the previous functionality, in which the return value (now under `Data`) was not checked.

2024-01-21 12:45 UTC, moshe-blox commented on go-eth2-client/client.go
> +	}
this should preserve the previous functionality, in which the return value (now under `Data`) was not checked.

2024-01-21 12:45 UTC, moshe-blox commented on go-eth2-client/client.go
> +	return resp, nil
this should preserve the previous functionality, in which the return value (now under `Data`) was not checked.

2024-01-21 12:46 UTC, moshe-blox commented on go-eth2-client/client.go
> +	return resp, nil
this should preserve the previous functionality, in which the return value (now under `Data`) was not checked.

2024-01-21 12:48 UTC, moshe-blox commented
> some places you check `Data` some not, lets unify

replied in comments, basically the idea is that the return value is now under `Data` so i assume that wherever we weren't checking it then we shouldn't have to check `Data` either

2024-01-21 12:51 UTC, olegshmuelov approved these changes

2024-01-21 13:35 UTC, y0sher approved these changes

2024-01-21 13:40 UTC, merged